import * as Types from "../../Types";

export const listOfPickaxes = {
  bronzepickaxe: {
    name: "bronzepickaxe",
    displayName: "Bronze pickaxe",
    levelReqMining: 1,
    penetration: 0,
    damageMin: 3,
    damageMax: 8,
    value: 168,
  },
  ironpickaxe: {
    name: "ironpickaxe",
    displayName: "Iron pickaxe",
    levelReqMining: 10,
    penetration: 5,
    damageMin: 5,
    damageMax: 15,
    value: 251,
  },
  steelpickaxe: {
    name: "steelpickaxe",
    displayName: "Steel pickaxe",
    levelReqMining: 20,
    penetration: 15,
    damageMin: 10,
    damageMax: 30,
    value: 334,
  },
  mithrilpickaxe: {
    name: "mithrilpickaxe",
    displayName: "Mithril pickaxe",
    levelReqMining: 30,
    penetration: 30,
    damageMin: 16,
    damageMax: 46,
    value: 501,
  },
  adamantpickaxe: {
    name: "adamantpickaxe",
    displayName: "Adamant pickaxe",
    levelReqMining: 40,
    penetration: 50,
    damageMin: 20,
    damageMax: 60,
    value: 668,
  },
  runepickaxe: {
    name: "runepickaxe",
    displayName: "Rune pickaxe",
    levelReqMining: 50,
    penetration: 75,
    damageMin: 25,
    damageMax: 75,
    value: 1668,
  },
  orikalkumpickaxe: {
    name: "orikalkumpickaxe",
    displayName: "Orikalkum pickaxe",
    levelReqMining: 60,
    penetration: 105,
    damageMin: 30,
    damageMax: 90,
    value: 3334,
  },
  dragonpickaxe: {
    name: "dragonpickaxe",
    displayName: "Dragon pickaxe",
    levelReqMining: 60,
    penetration: 105,
    damageMin: 33,
    damageMax: 93,
    value: 125000,
  },
  necroniumpickaxe: {
    name: "necroniumpickaxe",
    displayName: "Necronium pickaxe",
    levelReqMining: 70,
    penetration: 140,
    damageMin: 35,
    damageMax: 105,
    value: 6668,
  },
  //@ this is a special purchase
  crystalpickaxe: {
    name: "crystalpickaxe",
    displayName: "Crystal pickaxe",
    levelReqMining: 70,
    penetration: 140,
    damageMin: 39,
    damageMax: 109,
    value: 4000,
  },
  banepickaxe: {
    name: "banepickaxe",
    displayName: "Bane pickaxe",
    levelReqMining: 80,
    penetration: 185,
    damageMin: 40,
    damageMax: 120,
    value: 13334,
  },
  elderpickaxe: {
    name: "elderpickaxe",
    displayName: "Elder pickaxe",
    levelReqMining: 90,
    penetration: 235,
    damageMin: 45,
    damageMax: 135,
    value: 33334,
  },
};
