import * as Types from "../../Types";

const listOfMeleeHeads: Types.IListOfMeleeHeads = {
  bronzefullhelm: {
    name: `bronzefullhelm`,
    levelReqDefence: 1,
    tier: 5,
    armor: 5,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.02,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 168,
  },
  ironfullhelm: {
    name: "ironfullhelm",
    levelReqDefence: 10,
    tier: 10,
    armor: 40.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.2,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 251,
  },
  steelfullhelm: {
    name: "steelfullhelm",
    levelReqDefence: 20,
    tier: 20,
    armor: 63.2,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.4,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 334,
  },
  mithrilfullhelm: {
    name: "mithrilfullhelm",
    levelReqDefence: 30,
    tier: 30,
    armor: 90.8,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.6,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 501,
  },
  adamantfullhelm: {
    name: "adamantfullhelm",
    levelReqDefence: 40,
    tier: 40,
    armor: 125.6,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.8,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 668,
  },
  runefullhelm: {
    name: "runefullhelm",
    levelReqDefence: 50,
    tier: 50,
    armor: 170,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 1,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 1668,
  },
};
const listOfMagicHeads = {};
const listOfRangedHeads = {};

//! fill this out, maybe 1 or 2 for each style and slot
//! make a tool for this lol
