import * as Types from "../../Types";

const listOfMeleeBodies: Types.IListOfMeleeBodies = {
  bronzeplatebody: {
    name: "bronzeplatebody",
    displayName: `Bronze platebody`,
    levelReqDefence: 1,
    tier: 5,
    armor: 34.5,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.02,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 418,
  },
  ironplatebody: {
    name: "ironplatebody",
    displayName: `Iron platebody`,
    levelReqDefence: 10,
    tier: 10,
    armor: 46.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.2,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 626,
  },
  steelplatebody: {
    name: "steelplatebody",
    displayName: `Steel platebody`,
    levelReqDefence: 20,
    tier: 20,
    armor: 72.6,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.4,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 834,
  },
  mithrilplatebody: {
    name: "mithrilplatebody",
    displayName: `Mithril platebody`,
    levelReqDefence: 30,
    tier: 30,
    armor: 104.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.6,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 1251,
  },
  adamantplatebody: {
    name: "adamantplatebody",
    displayName: `Adamant platebody`,
    levelReqDefence: 40,
    tier: 40,
    armor: 144.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.8,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 1668,
  },
  runeplatebody: {
    name: "runeplatebody",
    displayName: `Rune platebody`,
    levelReqDefence: 50,
    tier: 50,
    armor: 195.5,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 1,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 4168,
  },
};
const listOfMagicBodies: Types.IListOfMagicBodies = {
  wizardrobetop: {
    name: "wizardrobetop",
    displayName: `Wizard robe top`,
    levelReqDefence: 0,
    tier: 1,
    armor: 25.3,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.02,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 15,
  },
  imphiderobetop: {
    name: "imphiderobetop",
    displayName: `Imphide robe top`,
    levelReqDefence: 10,
    tier: 10,
    armor: 46.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.2,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 500,
  },
  spidersilkrobetop: {
    name: "spidersilkrobetop",
    displayName: `Spider silk robe top`,
    levelReqDefence: 20,
    tier: 20,
    armor: 72.6,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.4,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 2000,
  },
  batwingtorso: {
    name: "batwingtorso",
    displayName: `Batwing torso`,
    levelReqDefence: 30,
    tier: 30,
    armor: 104.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.6,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 900,
  },
  splitbarkbody: {
    name: "splitbarkbody",
    displayName: `Splitbark body`,
    levelReqDefence: 40,
    tier: 40,
    armor: 144.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.8,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 45000,
  },
};
const listOfRangedBodies: Types.IListOfRangedBodies = {
  leatherbody: {
    name: "leatherbody",
    displayName: `Leather body`,
    levelReqDefence: 0,
    tier: 5,
    armor: 34.5,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.1,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 21,
  },
  hardleatherbody: {
    name: "hardleatherbody",
    displayName: `Hardleather body`,
    levelReqDefence: 10,
    tier: 10,
    armor: 46.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.2,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 170,
  },
  studdedbody: {
    name: "studdedbody",
    displayName: `Studded body`,
    levelReqDefence: 20,
    tier: 20,
    armor: 72.6,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.4,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 850,
  },
  carapacetorso: {
    name: "carapacetorso",
    displayName: `Carapace torso`,
    levelReqDefence: 30,
    tier: 30,
    armor: 104.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.6,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 900,
  },
  greendragonhidebody: {
    name: "greendragonhidebody",
    displayName: `Green dragonhide body`,
    levelReqDefence: 40,
    tier: 40,
    armor: 144.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.8,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 7800,
  },
};

export const BodySlot: Types.IArmorSlotBody = {
  bronzeplatebody: {
    name: "bronzeplatebody",
    displayName: `Bronze platebody`,
    levelReqDefence: 1,
    tier: 5,
    armor: 34.5,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.02,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 418,
  },
  ironplatebody: {
    name: "ironplatebody",
    displayName: `Iron platebody`,
    levelReqDefence: 10,
    tier: 10,
    armor: 46.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.2,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 626,
  },
  steelplatebody: {
    name: "steelplatebody",
    displayName: `Steel platebody`,
    levelReqDefence: 20,
    tier: 20,
    armor: 72.6,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.4,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 834,
  },
  mithrilplatebody: {
    name: "mithrilplatebody",
    displayName: `Mithril platebody`,
    levelReqDefence: 30,
    tier: 30,
    armor: 104.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.6,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 1251,
  },
  adamantplatebody: {
    name: "adamantplatebody",
    displayName: `Adamant platebody`,
    levelReqDefence: 40,
    tier: 40,
    armor: 144.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.8,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 1668,
  },
  runeplatebody: {
    name: "runeplatebody",
    displayName: `Rune platebody`,
    levelReqDefence: 50,
    tier: 50,
    armor: 195.5,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 1,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 4168,
  },
  wizardrobetop: {
    name: "wizardrobetop",
    displayName: `Wizard robe top`,
    levelReqDefence: 0,
    tier: 1,
    armor: 25.3,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.02,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 15,
  },
  imphiderobetop: {
    name: "imphiderobetop",
    displayName: `Imphide robe top`,
    levelReqDefence: 10,
    tier: 10,
    armor: 46.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.2,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 500,
  },
  spidersilkrobetop: {
    name: "spidersilkrobetop",
    displayName: `Spider silk robe top`,
    levelReqDefence: 20,
    tier: 20,
    armor: 72.6,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.4,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 2000,
  },
  batwingtorso: {
    name: "batwingtorso",
    displayName: `Batwing torso`,
    levelReqDefence: 30,
    tier: 30,
    armor: 104.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.6,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 900,
  },
  splitbarkbody: {
    name: "splitbarkbody",
    displayName: `Splitbark body`,
    levelReqDefence: 40,
    tier: 40,
    armor: 144.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.8,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 45000,
  },
  leatherbody: {
    name: "leatherbody",
    displayName: `Leather body`,
    levelReqDefence: 0,
    tier: 5,
    armor: 34.5,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.1,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 21,
  },
  hardleatherbody: {
    name: "hardleatherbody",
    displayName: `Hardleather body`,
    levelReqDefence: 10,
    tier: 10,
    armor: 46.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.2,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 170,
  },
  studdedbody: {
    name: "studdedbody",
    displayName: `Studded body`,
    levelReqDefence: 20,
    tier: 20,
    armor: 72.6,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.4,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 850,
  },
  carapacetorso: {
    name: "carapacetorso",
    displayName: `Carapace torso`,
    levelReqDefence: 30,
    tier: 30,
    armor: 104.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.6,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 900,
  },
  greendragonhidebody: {
    name: "greendragonhidebody",
    displayName: `Green dragonhide body`,
    levelReqDefence: 40,
    tier: 40,
    armor: 144.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.8,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 7800,
  },
};
