import * as Types from "../../Types";

const listOfMeleeHands: Types.IListOfMeleeHands = {
  bronzegauntlets: {
    name: "bronzegauntlets",
    displayName: `Bronze gauntlets`,
    levelReqDefence: 1,
    tier: 5,
    armor: 7.5,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.02,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 84,
  },
  irongauntlets: {
    name: "irongauntlets",
    displayName: `Iron gauntlets`,
    levelReqDefence: 10,
    tier: 10,
    armor: 10.1,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.2,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 126,
  },
  steelgauntlets: {
    name: "steelgauntlets",
    displayName: `Steel gauntlets`,
    levelReqDefence: 20,
    tier: 20,
    armor: 15.8,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.4,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 168,
  },
  mithrilgauntlets: {
    name: "mithrilgauntlets",
    displayName: `Mithril gauntlets`,
    levelReqDefence: 30,
    tier: 30,
    armor: 22.7,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.6,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 251,
  },
  adamantgauntlets: {
    name: "adamantgauntlets",
    displayName: `Adamant gauntlets`,
    levelReqDefence: 40,
    tier: 40,
    armor: 31.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.8,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 334,
  },
  runegauntlets: {
    name: "runegauntlets",
    displayName: `Rune gauntlets`,
    levelReqDefence: 50,
    tier: 50,
    armor: 42.5,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 1,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 834,
  },
};
const listOfMagicHands: Types.IListOfMagicHands = {
  wizardgloves: {
    name: "wizardgloves",
    displayName: `Wizard gloves`,
    levelReqDefence: 1,
    tier: 5,
    armor: 7.5,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.02,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 100,
  },
  imphidegloves: {
    name: "imphidegloves",
    displayName: `Imphide gloves`,
    levelReqDefence: 10,
    tier: 10,
    armor: 10.1,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.2,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 100,
  },
  spidersilkgloves: {
    name: "spidersilkgloves",
    displayName: `Spider silk gloves`,
    levelReqDefence: 20,
    tier: 20,
    armor: 15.8,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.4,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 300,
  },
  batwinggloves: {
    name: "batwinggloves",
    displayName: `Batwing gloves`,
    levelReqDefence: 30,
    tier: 30,
    armor: 22.7,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.6,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 200,
  },
  splitbarkgauntlets: {
    name: "splitbarkgauntlets",
    displayName: `Splitbark gauntlets`,
    levelReqDefence: 40,
    tier: 40,
    armor: 31.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.8,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 5000,
  },
};
const listOfRangedHands: Types.IListOfRangedHands = {
  leathervambraces: {
    name: "leathervambraces",
    displayName: `Leather vambraces`,
    levelReqDefence: 0,
    tier: 1,
    armor: 5.5,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.02,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 18,
  },
  hardleathergloves: {
    name: "hardleathergloves",
    displayName: `Hard leather gloves`,
    levelReqDefence: 10,
    tier: 10,
    armor: 10.1,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.2,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 200,
  },
  studdedleathergloves: {
    name: "studdedleathergloves",
    displayName: `Studded leather gloves`,
    levelReqDefence: 20,
    tier: 20,
    armor: 15.8,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.4,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 300,
  },
  carapacegloves: {
    name: "carapacegloves",
    displayName: `Carapace gloves`,
    levelReqDefence: 30,
    tier: 30,
    armor: 22.7,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.6,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 200,
  },
  greendragonhidevambraces: {
    name: "greendragonhidevambraces",
    displayName: `Green dragonhide vambraces`,
    levelReqDefence: 40,
    tier: 40,
    armor: 31.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.8,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 2500,
  },
};

export const HandsSlot: Types.IArmorSlotHands = {
  melee: listOfMeleeHands,
  magic: listOfMagicHands,
  ranged: listOfRangedHands,
};
