import * as Types from "../../Types";

const listOfMeleeLegs: Types.IListOfMeleeLegs = {
  bronzeplatelegs: {
    name: "bronzeplatelegs",
    displayName: `Bronze platelegs`,
    levelReqDefence: 1,
    tier: 5,
    armor: 33,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.02,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 251,
  },
  ironplatelegs: {
    name: "ironplatelegs",
    displayName: `Iron platelegs`,
    levelReqDefence: 10,
    tier: 10,
    armor: 44.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.2,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 376,
  },
  steelplatelegs: {
    name: "steelplatelegs",
    displayName: `Steel platelegs`,
    levelReqDefence: 20,
    tier: 20,
    armor: 69.5,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.4,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 501,
  },
  mithrilplatelegs: {
    name: "mithrilplatelegs",
    displayName: `Mithril platelegs`,
    levelReqDefence: 30,
    tier: 30,
    armor: 99.8,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.6,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 751,
  },
  adamantplatelegs: {
    name: "adamantplatelegs",
    displayName: `Adamant platelegs`,
    levelReqDefence: 40,
    tier: 40,
    armor: 138.1,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.8,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 1001,
  },
  runeplatelegs: {
    name: "runeplatelegs",
    displayName: `Rune platelegs`,
    levelReqDefence: 50,
    tier: 50,
    armor: 187,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 1,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 2501,
  },
};
const listOfMagicLegs: Types.IListOfMagicLegs = {
  wizardrobeskirt: {
    name: "wizardrobeskirt",
    displayName: `Wizard robe skirt`,
    levelReqDefence: 0,
    tier: 5,
    armor: 33,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.1,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 2,
  },
  imphiderobebottom: {
    name: "imphiderobebottom",
    displayName: `Imphide robe bottom`,
    levelReqDefence: 10,
    tier: 10,
    armor: 44.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.2,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 200,
  },
  spidersilkrobebottom: {
    name: "spidersilkrobebottom",
    displayName: `Spider silk robe bottom`,
    levelReqDefence: 20,
    tier: 20,
    armor: 69.5,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.4,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 1500,
  },
  batwinglegs: {
    name: "batwinglegs",
    displayName: `Batwing legs`,
    levelReqDefence: 30,
    tier: 30,
    armor: 99.8,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.6,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 700,
  },
  splitbarklegs: {
    name: "splitbarklegs",
    displayName: `Splitbark legs`,
    levelReqDefence: 40,
    tier: 40,
    armor: 138.1,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.8,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 40000,
  },
};
const listOfRangedLegs: Types.IListOfRangedLegs = {
  leatherchaps: {
    name: "leatherchaps",
    displayName: `Leather chaps`,
    levelReqDefence: 0,
    tier: 5,
    armor: 33,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.1,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 20,
  },
  hardleatherchaps: {
    name: "hardleatherchaps",
    displayName: `Hard leather chaps`,
    levelReqDefence: 10,
    tier: 10,
    armor: 44.4,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.2,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 170,
  },
  studdedchaps: {
    name: "studdedchaps",
    displayName: `Studded chaps`,
    levelReqDefence: 20,
    tier: 20,
    armor: 69.5,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.4,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 750,
  },
  carapacelegs: {
    name: "carapacelegs",
    displayName: `Carapace legs`,
    levelReqDefence: 30,
    tier: 30,
    armor: 99.8,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.6,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 700,
  },
  greendragonhidechaps: {
    name: "greendragonhidechaps",
    displayName: `Green dragonhide chaps`,
    levelReqDefence: 40,
    tier: 40,
    armor: 138.1,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0.8,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 3900,
  },
};

export const legSlot: Types.IArmorSlotLegs = {
  melee: listOfMeleeLegs,
  magic: listOfMagicLegs,
  ranged: listOfRangedLegs,
};
