import * as Types from "../../Types";

//! for now, just use 2h weapons, since magic already needs to track ammunition in the form of runes

const listOfMeleeMainHands = {
  bronzelongsword: {
    name: "bronzelongsword",
    levelReqAttack: 1,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 5,
    damage: 61.3,
    accuracy: 150,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 168,
  },
  ironlongsword: {
    name: "ironlongsword",
    levelReqAttack: 10,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 10,
    damage: 122.5,
    accuracy: 202,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 251,
  },
  steellongsword: {
    name: "steellongsword",
    levelReqAttack: 20,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 20,
    damage: 245,
    accuracy: 316,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 334,
  },
  mithrillongsword: {
    name: "mithrillongsword",
    levelReqAttack: 30,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 30,
    damage: 367.5,
    accuracy: 454,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 501,
  },
  adamantlongsword: {
    name: "adamantlongsword",
    levelReqAttack: 40,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 40,
    damage: 490,
    accuracy: 628,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 668,
  },
  runelongsword: {
    name: "runelongsword",
    levelReqAttack: 50,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 50,
    damage: 612.5,
    accuracy: 850,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 1668,
  },
};
const listOfMagicMainHands = {
  wizardwand: {
    name: "wizardwand",
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 1,
    levelReqRanged: 0,
    tier: 5,
    damage: 0,
    accuracy: 150,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 100,
  },
  imphornwand: {
    name: "imphornwand",
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 10,
    levelReqRanged: 0,
    tier: 10,
    damage: 0,
    accuracy: 202,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 250,
  },
  spiderwand: {
    name: "spiderwand",
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 20,
    levelReqRanged: 0,
    tier: 20,
    damage: 0,
    accuracy: 316,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 500,
  },
  batwingwand: {
    name: "batwingwand",
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 30,
    levelReqRanged: 0,
    tier: 30,
    damage: 0,
    accuracy: 454,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 600,
  },
  splitbarkwand: {
    name: "splitbarkwand",
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 40,
    levelReqRanged: 0,
    tier: 40,
    damage: 0,
    accuracy: 628,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 2000,
  },
};
const listOfRangedMainHands = {
  bronzeknife: {
    name: "bronzeknife",
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 1,
    tier: 5,
    damage: 48,
    accuracy: 150,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 4,
  },
  ironknife: {
    name: "ironknife",
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 10,
    tier: 10,
    damage: 96,
    accuracy: 202,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 6,
  },
  steelknife: {
    name: "steelknife",
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 20,
    tier: 20,
    damage: 192,
    accuracy: 316,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 9,
  },
  mithrilknife: {
    name: "mithrilknife",
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 30,
    tier: 30,
    damage: 288,
    accuracy: 454,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 16,
  },
  adamantknife: {
    name: "adamantknife",
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 40,
    tier: 40,
    damage: 384,
    accuracy: 628,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 15,
  },
  runeknife: {
    name: "runeknife",
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 50,
    tier: 50,
    damage: 480,
    accuracy: 850,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 40,
  },
};

export const mainHandSlot = {
  melee: listOfMeleeMainHands,
  magic: listOfMagicMainHands,
  ranged: listOfRangedMainHands,
};
