import * as Types from "../../Types";

const listOfMeleeTwoHanders: Types.IListOfMeleeTwoHand = {
  bronze2hsword: {
    name: "bronze2hsword",
    displayName: `Bronze 2h sword`,
    thisWeaponStyle: `melee`,
    levelReqAttack: 1,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 5,
    armor: 0,
    damage: 111.8,
    accuracy: 150,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: `typeless`,
    value: 334,
  },
  iron2hsword: {
    name: "iron2hsword",
    displayName: `Iron 2h sword`,
    thisWeaponStyle: `melee`,
    levelReqAttack: 10,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 10,
    armor: 0,
    damage: 223.5,
    accuracy: 202,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: `typeless`,
    value: 501,
  },
  steel2hsword: {
    name: "steel2hsword",
    displayName: `Steel 2h sword`,
    thisWeaponStyle: `melee`,
    levelReqAttack: 20,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 20,
    armor: 0,
    damage: 447,
    accuracy: 316,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: `typeless`,
    value: 668,
  },
  mithril2hsword: {
    name: "mithril2hsword",
    displayName: `Mithril 2h sword`,
    thisWeaponStyle: `melee`,
    levelReqAttack: 30,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 30,
    armor: 0,
    damage: 670.5,
    accuracy: 454,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: `typeless`,
    value: 1001,
  },
  adamant2hsword: {
    name: "adamant2hsword",
    displayName: `Adamant 2h sword`,
    thisWeaponStyle: `melee`,
    levelReqAttack: 40,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 40,
    armor: 0,
    damage: 894,
    accuracy: 628,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: `typeless`,
    value: 1334,
  },
  rune2hsword: {
    name: "rune2hsword",
    displayName: `Rune 2h sword`,
    thisWeaponStyle: `melee`,
    levelReqAttack: 50,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 50,
    armor: 0,
    damage: 1117.5,
    accuracy: 850,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: `typeless`,
    value: 3334,
  },
};
const listOfMagicTwoHanders: Types.IListOfMagicTwoHand = {
  staffofair: {
    name: "staffofair",
    displayName: `Staff of air`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 5,
    armor: 0,
    damage: 0,
    accuracy: 150,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: `air`,
    value: 1500,
  },
  staffofwater: {
    name: "staffofwater",
    displayName: `Staff of water`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 5,
    armor: 0,
    damage: 0,
    accuracy: 150,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: `water`,
    value: 1500,
  },
  staffofearth: {
    name: "staffofearth",
    displayName: `Staff of earth`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 5,
    armor: 0,
    damage: 0,
    accuracy: 150,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: `earth`,
    value: 1500,
  },
  staffoffire: {
    name: "staffoffire",
    displayName: `Staff of fire`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 5,
    armor: 0,
    damage: 0,
    accuracy: 150,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: `fire`,
    value: 1500,
  },
  airbattlestaff: {
    name: "airbattlestaff",
    displayName: `Air battlestaff`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 30,
    levelReqRanged: 0,
    tier: 30,
    armor: 0,
    damage: 0,
    accuracy: 454,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "air",
    value: 15500,
  },
  waterbattlestaff: {
    name: "waterbattlestaff",
    displayName: `Water battlestaff`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 30,
    levelReqRanged: 0,
    tier: 30,
    armor: 0,
    damage: 0,
    accuracy: 454,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "water",
    value: 15500,
  },
  earthbattlestaff: {
    name: "earthbattlestaff",
    displayName: `Earth battlestaff`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 30,
    levelReqRanged: 0,
    tier: 30,
    armor: 0,
    damage: 0,
    accuracy: 454,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "earth",
    value: 15500,
  },
  firebattlestaff: {
    name: "firebattlestaff",
    displayName: `Fire battlestaff`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 30,
    levelReqRanged: 0,
    tier: 30,
    armor: 0,
    damage: 0,
    accuracy: 454,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "fire",
    value: 15500,
  },
  mysticairstaff: {
    name: "mysticairstaff",
    displayName: `Mystic air staff`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 40,
    levelReqRanged: 0,
    tier: 40,
    armor: 0,
    damage: 0,
    accuracy: 628,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "air",
    value: 42500,
  },
  mysticwaterstaff: {
    name: "mysticwaterstaff",
    displayName: `Mystic water staff`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 40,
    levelReqRanged: 0,
    tier: 40,
    armor: 0,
    damage: 0,
    accuracy: 628,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "water",
    value: 42500,
  },
  mysticearthstaff: {
    name: "mysticearthstaff",
    displayName: `Mystic earth staff`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 40,
    levelReqRanged: 0,
    tier: 40,
    armor: 0,
    damage: 0,
    accuracy: 628,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "earth",
    value: 42500,
  },
  mysticfirestaff: {
    name: "mysticfirestaff",
    displayName: `Mystic fire staff`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 40,
    levelReqRanged: 0,
    tier: 40,
    armor: 0,
    damage: 0,
    accuracy: 628,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "fire",
    value: 42500,
  },
};
const listOfRangedTwoHanders: Types.IListOfRangedTwoHand = {
  shortbow: {
    name: "shortbow",
    displayName: `Shortbow`,
    thisWeaponStyle: `ranged`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 5,
    armor: 0,
    damage: 43.9,
    accuracy: 150,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "typeless",
    value: 50,
  },
  oakshortbow: {
    name: "oakshortbow",
    displayName: `Oak shortbow`,
    thisWeaponStyle: `ranged`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 10,
    tier: 10,
    armor: 0,
    damage: 87.8,
    accuracy: 202,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "typeless",
    value: 100,
  },
  willowshortbow: {
    name: "willowshortbow",
    displayName: `Willow shortbow`,
    thisWeaponStyle: `ranged`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 20,
    tier: 20,
    armor: 0,
    damage: 175.5,
    accuracy: 316,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "typeless",
    value: 200,
  },
  mapleshortbow: {
    name: "mapleshortbow",
    displayName: `Maple shortbow`,
    thisWeaponStyle: `ranged`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 30,
    tier: 30,
    armor: 0,
    damage: 263.3,
    accuracy: 454,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "typeless",
    value: 400,
  },
  yewshortbow: {
    name: "yewshortbow",
    displayName: `Yew shortbow`,
    thisWeaponStyle: `ranged`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 40,
    tier: 40,
    armor: 0,
    damage: 351,
    accuracy: 628,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "typeless",
    value: 800,
  },
  magicshortbow: {
    name: "magicshortbow",
    displayName: `Magic shortbow`,
    thisWeaponStyle: `ranged`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 50,
    tier: 50,
    armor: 0,
    damage: 438.8,
    accuracy: 850,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "typeless",
    value: 1600,
  },
};

export const TwoHandSlot: Types.IArmorSlotTwoHand = {
  none: {
    name: "none",
    displayName: `None`,
    levelReqDefence: -1,
    tier: 0,
    armor: 0,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    value: 0,
  },
  bronze2hsword: {
    name: "bronze2hsword",
    displayName: `Bronze 2h sword`,
    thisWeaponStyle: `melee`,
    levelReqAttack: 1,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 5,
    armor: 0,
    damage: 111.8,
    accuracy: 150,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: `typeless`,
    value: 334,
  },
  iron2hsword: {
    name: "iron2hsword",
    displayName: `Iron 2h sword`,
    thisWeaponStyle: `melee`,
    levelReqAttack: 10,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 10,
    armor: 0,
    damage: 223.5,
    accuracy: 202,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: `typeless`,
    value: 501,
  },
  steel2hsword: {
    name: "steel2hsword",
    displayName: `Steel 2h sword`,
    thisWeaponStyle: `melee`,
    levelReqAttack: 20,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 20,
    armor: 0,
    damage: 447,
    accuracy: 316,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: `typeless`,
    value: 668,
  },
  mithril2hsword: {
    name: "mithril2hsword",
    displayName: `Mithril 2h sword`,
    thisWeaponStyle: `melee`,
    levelReqAttack: 30,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 30,
    armor: 0,
    damage: 670.5,
    accuracy: 454,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: `typeless`,
    value: 1001,
  },
  adamant2hsword: {
    name: "adamant2hsword",
    displayName: `Adamant 2h sword`,
    thisWeaponStyle: `melee`,
    levelReqAttack: 40,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 40,
    armor: 0,
    damage: 894,
    accuracy: 628,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: `typeless`,
    value: 1334,
  },
  rune2hsword: {
    name: "rune2hsword",
    displayName: `Rune 2h sword`,
    thisWeaponStyle: `melee`,
    levelReqAttack: 50,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 50,
    armor: 0,
    damage: 1117.5,
    accuracy: 850,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: `typeless`,
    value: 3334,
  },

  staffofair: {
    name: "staffofair",
    displayName: `Staff of air`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 5,
    armor: 0,
    damage: 0,
    accuracy: 150,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: `air`,
    value: 1500,
  },
  staffofwater: {
    name: "staffofwater",
    displayName: `Staff of water`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 5,
    armor: 0,
    damage: 0,
    accuracy: 150,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: `water`,
    value: 1500,
  },
  staffofearth: {
    name: "staffofearth",
    displayName: `Staff of earth`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 5,
    armor: 0,
    damage: 0,
    accuracy: 150,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: `earth`,
    value: 1500,
  },
  staffoffire: {
    name: "staffoffire",
    displayName: `Staff of fire`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 5,
    armor: 0,
    damage: 0,
    accuracy: 150,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: `fire`,
    value: 1500,
  },
  airbattlestaff: {
    name: "airbattlestaff",
    displayName: `Air battlestaff`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 30,
    levelReqRanged: 0,
    tier: 30,
    armor: 0,
    damage: 0,
    accuracy: 454,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "air",
    value: 15500,
  },
  waterbattlestaff: {
    name: "waterbattlestaff",
    displayName: `Water battlestaff`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 30,
    levelReqRanged: 0,
    tier: 30,
    armor: 0,
    damage: 0,
    accuracy: 454,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "water",
    value: 15500,
  },
  earthbattlestaff: {
    name: "earthbattlestaff",
    displayName: `Earth battlestaff`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 30,
    levelReqRanged: 0,
    tier: 30,
    armor: 0,
    damage: 0,
    accuracy: 454,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "earth",
    value: 15500,
  },
  firebattlestaff: {
    name: "firebattlestaff",
    displayName: `Fire battlestaff`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 30,
    levelReqRanged: 0,
    tier: 30,
    armor: 0,
    damage: 0,
    accuracy: 454,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "fire",
    value: 15500,
  },
  mysticairstaff: {
    name: "mysticairstaff",
    displayName: `Mystic air staff`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 40,
    levelReqRanged: 0,
    tier: 40,
    armor: 0,
    damage: 0,
    accuracy: 628,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "air",
    value: 42500,
  },
  mysticwaterstaff: {
    name: "mysticwaterstaff",
    displayName: `Mystic water staff`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 40,
    levelReqRanged: 0,
    tier: 40,
    armor: 0,
    damage: 0,
    accuracy: 628,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "water",
    value: 42500,
  },
  mysticearthstaff: {
    name: "mysticearthstaff",
    displayName: `Mystic earth staff`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 40,
    levelReqRanged: 0,
    tier: 40,
    armor: 0,
    damage: 0,
    accuracy: 628,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "earth",
    value: 42500,
  },
  mysticfirestaff: {
    name: "mysticfirestaff",
    displayName: `Mystic fire staff`,
    thisWeaponStyle: `magic`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 40,
    levelReqRanged: 0,
    tier: 40,
    armor: 0,
    damage: 0,
    accuracy: 628,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "fire",
    value: 42500,
  },
  shortbow: {
    name: "shortbow",
    displayName: `Shortbow`,
    thisWeaponStyle: `ranged`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 0,
    tier: 5,
    armor: 0,
    damage: 43.9,
    accuracy: 150,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "typeless",
    value: 50,
  },
  oakshortbow: {
    name: "oakshortbow",
    displayName: `Oak shortbow`,
    thisWeaponStyle: `ranged`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 10,
    tier: 10,
    armor: 0,
    damage: 87.8,
    accuracy: 202,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "typeless",
    value: 100,
  },
  willowshortbow: {
    name: "willowshortbow",
    displayName: `Willow shortbow`,
    thisWeaponStyle: `ranged`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 20,
    tier: 20,
    armor: 0,
    damage: 175.5,
    accuracy: 316,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "typeless",
    value: 200,
  },
  mapleshortbow: {
    name: "mapleshortbow",
    displayName: `Maple shortbow`,
    thisWeaponStyle: `ranged`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 30,
    tier: 30,
    armor: 0,
    damage: 263.3,
    accuracy: 454,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "typeless",
    value: 400,
  },
  yewshortbow: {
    name: "yewshortbow",
    displayName: `Yew shortbow`,
    thisWeaponStyle: `ranged`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 40,
    tier: 40,
    armor: 0,
    damage: 351,
    accuracy: 628,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "typeless",
    value: 800,
  },
  magicshortbow: {
    name: "magicshortbow",
    displayName: `Magic shortbow`,
    thisWeaponStyle: `ranged`,
    levelReqAttack: 0,
    levelReqStrength: 0,
    levelReqMagic: 0,
    levelReqRanged: 50,
    tier: 50,
    armor: 0,
    damage: 438.8,
    accuracy: 850,
    lifePointsExtra: 0,
    prayerPointsExtra: 0,
    damageReduction: 0,
    styleBonusMelee: 0,
    styleBonusRanged: 0,
    styleBonusMagic: 0,
    staffElement: "typeless",
    value: 1600,
  },
};
