import * as Types from "../../Types";
export const ListOfFish: Types.IListOfFish = {
  shrimp: {
    name: `shrimp`,
    levelReqFishing: 1,
    XPGivenFishing: 10,
    levelReqCooking: 1,
    XPGivenCooking: 30,
    stopBurnLevel: 34,
    value: 6,
  },
  crayfish: {
    name: `crayfish`,
    levelReqFishing: 1,
    XPGivenFishing: 10,
    levelReqCooking: 1,
    XPGivenCooking: 30,
    stopBurnLevel: 34,
    value: 5,
  },
  anchovies: {
    name: `anchovies`,
    levelReqFishing: 15,
    XPGivenFishing: 40,
    levelReqCooking: 1,
    XPGivenCooking: 30,
    stopBurnLevel: 34,
    value: 16,
  },
  trout: {
    name: `trout`,
    levelReqFishing: 20,
    XPGivenFishing: 50,
    levelReqCooking: 15,
    XPGivenCooking: 70,
    stopBurnLevel: 50,
    value: 20,
  },
  salmon: {
    name: `salmon`,
    levelReqFishing: 30,
    XPGivenFishing: 70,
    levelReqCooking: 25,
    XPGivenCooking: 94,
    stopBurnLevel: 58,
    value: 92,
  },
  pike: {
    name: `pike`,
    levelReqFishing: 25,
    XPGivenFishing: 60,
    levelReqCooking: 20,
    XPGivenCooking: 80,
    stopBurnLevel: 53,
    value: 25,
  },
  sardine: {
    name: `sardine`,
    levelReqFishing: 5,
    XPGivenFishing: 20,
    levelReqCooking: 1,
    XPGivenCooking: 40,
    stopBurnLevel: 38,
    value: 10,
  },
  herring: {
    name: `herring`,
    levelReqFishing: 25,
    XPGivenFishing: 60,
    levelReqCooking: 20,
    XPGivenCooking: 80,
    stopBurnLevel: 41,
    value: 16,
  },
};
