import * as Types from "../../Types";
const ListOfLogs: Types.IListOfLogs = {
  logs: {
    name: `logs`,
    levelReqWoodcutting: 1,
    XPGivenWoodcutting: 25,
    levelReqFiremaking: 1,
    XPGivenFiremaking: 40,
    value: 4,
  },
  oak: {
    name: `oak`,
    levelReqWoodcutting: 15,
    XPGivenWoodcutting: 37.5,
    levelReqFiremaking: 15,
    XPGivenFiremaking: 60,
    value: 20,
  },
  willow: {
    name: `willow`,
    levelReqWoodcutting: 30,
    XPGivenWoodcutting: 67.5,
    levelReqFiremaking: 30,
    XPGivenFiremaking: 90,
    value: 40,
  },
  maple: {
    name: `maple`,
    levelReqWoodcutting: 45,
    XPGivenWoodcutting: 100,
    levelReqFiremaking: 45,
    XPGivenFiremaking: 135.5,
    value: 80,
  },
  yew: {
    name: `yew`,
    levelReqWoodcutting: 60,
    XPGivenWoodcutting: 175,
    levelReqFiremaking: 60,
    XPGivenFiremaking: 202.5,
    value: 160,
  },
  magic: {
    name: `magic`,
    levelReqWoodcutting: 75,
    XPGivenWoodcutting: 250,
    levelReqFiremaking: 75,
    XPGivenFiremaking: 303.8,
    value: 320,
  },
  elder: {
    name: `elder`,
    levelReqWoodcutting: 90,
    XPGivenWoodcutting: 325,
    levelReqFiremaking: 90,
    XPGivenFiremaking: 450,
    value: 480,
  },
};
