import * as Types from "../../Types";

export const ListOfOres: Types.IListOfOres = {
  runeEssence: {
    name: "runeEssence",
    displayName: "Rune essence",
    levelReqMining: 1,
    durability: 50,
    hardness: 0,
    xpMultiplier: 0.66,
    value: 17,
  },
  pureEssence: {
    name: "pureEssence",
    displayName: "Pure essence",
    levelReqMining: 30,
    durability: 50,
    hardness: 0,
    xpMultiplier: 0.66,
    value: 17,
  },
  tin: {
    name: "tin",
    displayName: "Tin ore",
    levelReqMining: 1,
    durability: 40,
    hardness: 0,
    xpMultiplier: 0.66,
    value: 17,
  },
  copper: {
    name: "copper",
    displayName: "Copper ore",
    levelReqMining: 1,
    durability: 40,
    hardness: 0,
    xpMultiplier: 0.66,
    value: 17,
  },
  iron: {
    name: "iron",
    displayName: "Iron ore",
    levelReqMining: 10,
    durability: 120,
    hardness: 5,
    xpMultiplier: 0.68,
    value: 25,
  },
  coal: {
    name: "coal",
    displayName: "Coal ore",
    levelReqMining: 20,
    durability: 140,
    hardness: 15,
    xpMultiplier: 0.7,
    value: 42,
  },
  mithril: {
    name: "mithril",
    displayName: "Mithril ore",
    levelReqMining: 30,
    durability: 240,
    hardness: 30,
    xpMultiplier: 0.72,
    value: 59,
  },
  gold: {
    name: "gold",
    displayName: "Gold ore",
    levelReqMining: 40,
    durability: 200,
    hardness: 50,
    xpMultiplier: 0.74,
    value: 150,
  },
  adamantite: {
    name: "adamantite",
    displayName: "Adamantite ore",
    levelReqMining: 40,
    durability: 380,
    hardness: 50,
    xpMultiplier: 0.74,
    value: 84,
  },
  luminite: {
    name: "luminite",
    displayName: "Luminite ore",
    levelReqMining: 40,
    durability: 380,
    hardness: 50,
    xpMultiplier: 0.74,
    value: 84,
  },
  runite: {
    name: "runite",
    displayName: "Runite ore",
    levelReqMining: 50,
    durability: 600,
    hardness: 75,
    xpMultiplier: 0.76,
    value: 209,
  },
  orichalcite: {
    name: "orichalcite",
    displayName: "Orichalcite ore",
    levelReqMining: 60,
    durability: 1400,
    hardness: 105,
    xpMultiplier: 0.78,
    value: 417,
  },
  drakolith: {
    name: "drakolith",
    displayName: "Drakolith ore",
    levelReqMining: 60,
    durability: 1400,
    hardness: 105,
    xpMultiplier: 0.78,
    value: 417,
  },
  necrite: {
    name: "necrite",
    displayName: "Necrite ore",
    levelReqMining: 70,
    durability: 1300,
    hardness: 140,
    xpMultiplier: 0.8,
    value: 834,
  },
  phasmatite: {
    name: "phasmatite",
    displayName: "Phasmatite ore",
    levelReqMining: 70,
    durability: 1300,
    hardness: 140,
    xpMultiplier: 0.8,
    value: 834,
  },
  banite: {
    name: "banite",
    displayName: "Banite ore",
    levelReqMining: 80,
    durability: 1700,
    hardness: 185,
    xpMultiplier: 0.82,
    value: 1067,
  },
  lightAnimica: {
    name: "lightAnimica",
    displayName: "Light animica ore",
    levelReqMining: 90,
    durability: 2000,
    hardness: 235,
    xpMultiplier: 0.84,
    value: 1734,
  },
  darkAnimica: {
    name: "darkAnimica",
    displayName: "Dark animica ore",
    levelReqMining: 90,
    durability: 2000,
    hardness: 235,
    xpMultiplier: 0.84,
    value: 1734,
  },
};
